# Generated by Django 4.2.7 on 2025-09-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantproduct',
            name='primary_image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
