# Generated by Django 4.2.7 on 2025-09-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_merchantproduct_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantproduct',
            name='ecoscore_calculation_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='merchantproduct',
            name='ecoscore_grade',
            field=models.CharField(blank=True, choices=[('A', 'A - Highly Sustainable'), ('B', 'B - Good'), ('C', 'C - Average'), ('D', 'D - Poor'), ('E', 'E - Very Poor')], max_length=1),
        ),
        migrations.AddField(
            model_name='merchantproduct',
            name='ecoscore_last_calculated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantproduct',
            name='ecoscore_value',
            field=models.FloatField(default=0.0, help_text='EcoScore value (0-100)'),
        ),
    ]
