# Generated by Django 4.2.7 on 2025-09-20 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchantproduct_ecoscore_calculation_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='state',
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Postal code must be 6 digits', regex='^[0-9]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='merchants.merchantprofile')),
            ],
        ),
    ]
